pub fn render_contract() -> Result<String, ts_rs::ExportError> {
    let cfg = Config::new();
    let mut contract = String::from(
        "// This file is generated by `pnpm ipc:generate`. Do not edit it by hand.\n\n",
    );

    for generated in [
        IpcErrorCode::export_to_string(&cfg)?,
        IpcError::export_to_string(&cfg)?,
        WorkspaceSummaryDto::export_to_string(&cfg)?,
        WorkspaceSnapshotDto::export_to_string(&cfg)?,
        CreateWorkspaceInput::export_to_string(&cfg)?,
        RenameWorkspaceInput::export_to_string(&cfg)?,
        SetWorkspaceBaseDirectoryInput::export_to_string(&cfg)?,
        WorkspaceIdInput::export_to_string(&cfg)?,
        OrderedFieldDto::export_to_string(&cfg)?,
        BodyFilePathDto::export_to_string(&cfg)?,
        BodyFileReferenceDto::export_to_string(&cfg)?,
        DescribeBodyFileInput::export_to_string(&cfg)?,
        RelinkBodyFilesInput::export_to_string(&cfg)?,
        MultipartPartDto::export_to_string(&cfg)?,
        RequestBodyDto::export_to_string(&cfg)?,
        ApiKeyPlacementDto::export_to_string(&cfg)?,
        RequestAuthDto::export_to_string(&cfg)?,
        RedirectPolicyDto::export_to_string(&cfg)?,
        TlsPolicyDto::export_to_string(&cfg)?,
        ProxySourceDto::export_to_string(&cfg)?,
        ProxyPolicyDto::export_to_string(&cfg)?,
        TimeoutPolicyDto::export_to_string(&cfg)?,
        TransportPolicyDto::export_to_string(&cfg)?,
        RequestContentDto::export_to_string(&cfg)?,
        SavedRequestDto::export_to_string(&cfg)?,
        CollectionFolderDto::export_to_string(&cfg)?,
        EnvironmentDto::export_to_string(&cfg)?,
        VariableValueDto::export_to_string(&cfg)?,
        VariableDto::export_to_string(&cfg)?,
        CollectionVariableDto::export_to_string(&cfg)?,
        EnvironmentVariableDto::export_to_string(&cfg)?,
        RequestDraftDto::export_to_string(&cfg)?,
        RequestTabDto::export_to_string(&cfg)?,
        RequestWorkspaceSnapshotDto::export_to_string(&cfg)?,
        PostmanImportInput::export_to_string(&cfg)?,
        PostmanExportInput::export_to_string(&cfg)?,
        PostmanExportResultDto::export_to_string(&cfg)?,
        PostmanEnvironmentExportDto::export_to_string(&cfg)?,
        PostmanImportPreviewDto::export_to_string(&cfg)?,
        PostmanImportWarningDto::export_to_string(&cfg)?,
        PostmanUnsupportedFieldDto::export_to_string(&cfg)?,
        PostmanImportResultDto::export_to_string(&cfg)?,
        PostmanReimportPreviewDto::export_to_string(&cfg)?,
        PostmanPriorImportDto::export_to_string(&cfg)?,
        PostmanReimportChangeDto::export_to_string(&cfg)?,
        PostmanReimportDecisionDto::export_to_string(&cfg)?,
        PostmanReimportInput::export_to_string(&cfg)?,
        PostmanReimportResultDto::export_to_string(&cfg)?,
        NativeBackupExportInput::export_to_string(&cfg)?,
        NativeBackupRestorePreviewInput::export_to_string(&cfg)?,
        NativeBackupRestoreInput::export_to_string(&cfg)?,
        NativeBackupExportResultDto::export_to_string(&cfg)?,
        NativeBackupRestoreResultDto::export_to_string(&cfg)?,
        NativeBackupRestorePreviewDto::export_to_string(&cfg)?,
        NativeBackupExclusionDto::export_to_string(&cfg)?,
        NativeBackupManifestDto::export_to_string(&cfg)?,
        NativeBackupManifestEntryDto::export_to_string(&cfg)?,
        DatabaseRecoveryStateDto::export_to_string(&cfg)?,
        DatabaseRecoveryModeDto::export_to_string(&cfg)?,
        RecoverableDatabaseExportInput::export_to_string(&cfg)?,
        RecoverableDatabaseExportDto::export_to_string(&cfg)?,
        DiagnosticDebugLoggingInput::export_to_string(&cfg)?,
        DiagnosticBundleExportInput::export_to_string(&cfg)?,
        DiagnosticBundlePreviewDto::export_to_string(&cfg)?,
        DiagnosticDebugLoggingStatusDto::export_to_string(&cfg)?,
        DiagnosticBundleExportDto::export_to_string(&cfg)?,
        UpdateCheckResultDto::export_to_string(&cfg)?,
        CurlImportInput::export_to_string(&cfg)?,
        CurlGenerateInput::export_to_string(&cfg)?,
        CurlImportPreviewDto::export_to_string(&cfg)?,
        CurlImportWarningDto::export_to_string(&cfg)?,
        CurlUnsupportedFieldDto::export_to_string(&cfg)?,
        CurlImportResultDto::export_to_string(&cfg)?,
        CurlGenerateResultDto::export_to_string(&cfg)?,
        ExecutionHistorySnapshotDto::export_to_string(&cfg)?,
        ExecutionRecordDto::export_to_string(&cfg)?,
        ExecutionRecordResponseDto::export_to_string(&cfg)?,
        CookieSameSiteDto::export_to_string(&cfg)?,
        WorkspaceCookieDto::export_to_string(&cfg)?,
        CookieJarSnapshotDto::export_to_string(&cfg)?,
        UpsertCookieInput::export_to_string(&cfg)?,
        CookieIdInput::export_to_string(&cfg)?,
        RevealCookieValueOutput::export_to_string(&cfg)?,
        CreateSavedRequestInput::export_to_string(&cfg)?,
        CollectionLocationDto::export_to_string(&cfg)?,
        SelectEnvironmentInput::export_to_string(&cfg)?,
        ResolveRequestContentInput::export_to_string(&cfg)?,
        ResolvedRequestContentDto::export_to_string(&cfg)?,
        ResolvedFieldDto::export_to_string(&cfg)?,
        ResolvedValueDto::export_to_string(&cfg)?,
        ResolvedVariableReferenceDto::export_to_string(&cfg)?,
        VariableSourceDto::export_to_string(&cfg)?,
        VariableResolutionErrorDto::export_to_string(&cfg)?,
        VariableResolutionErrorKindDto::export_to_string(&cfg)?,
        CreateCollectionFolderInput::export_to_string(&cfg)?,
        RenameCollectionFolderInput::export_to_string(&cfg)?,
        MoveCollectionFolderInput::export_to_string(&cfg)?,
        CollectionFolderIdInput::export_to_string(&cfg)?,
        MoveSavedRequestInput::export_to_string(&cfg)?,
        SavedRequestIdInput::export_to_string(&cfg)?,
        OpenSavedRequestTabInput::export_to_string(&cfg)?,
        UpdateRequestDraftInput::export_to_string(&cfg)?,
        RequestDraftIdInput::export_to_string(&cfg)?,
        CloseTabDecisionDto::export_to_string(&cfg)?,
        CloseRequestTabInput::export_to_string(&cfg)?,
        SetExecutionHistoryDisabledInput::export_to_string(&cfg)?,
        SetExecutionRecordPinnedInput::export_to_string(&cfg)?,
        ExecutionRecordIdInput::export_to_string(&cfg)?,
        StartRequestExecutionInput::export_to_string(&cfg)?,
        StartRequestExecutionOutput::export_to_string(&cfg)?,
        CancelRequestExecutionInput::export_to_string(&cfg)?,
        CancelRequestExecutionOutput::export_to_string(&cfg)?,
        SaveResponseFileInput::export_to_string(&cfg)?,
        SaveResponseFileOutput::export_to_string(&cfg)?,
        StartOAuthAuthorizationInput::export_to_string(&cfg)?,
        OAuthAuthorizationResultDto::export_to_string(&cfg)?,
        CancelOAuthAuthorizationInput::export_to_string(&cfg)?,
        CancelOAuthAuthorizationOutput::export_to_string(&cfg)?,
        ExecutionEventDto::export_to_string(&cfg)?,
        ExecutionEventKindDto::export_to_string(&cfg)?,
        ExecutionHeaderDto::export_to_string(&cfg)?,
        ResponseFileMetadataDto::export_to_string(&cfg)?,
        ExecutionProxyMetadataDto::export_to_string(&cfg)?,
        ExecutionTimeoutMetadataDto::export_to_string(&cfg)?,
        ExecutionTimingMetadataDto::export_to_string(&cfg)?,
    ] {
        let generated_without_imports = generated
            .lines()
            .filter(|line| !line.starts_with("import type "))
            .collect::<Vec<_>>()
            .join("\n");
        contract.push_str(generated_without_imports.trim());
        contract.push_str("\n\n");
    }

    contract.push_str(
        "export type WorkspaceCommandContracts = {\n\
         \tlist_workspaces: {\n\
         \t\tinput: undefined;\n\
         \t\toutput: WorkspaceSnapshotDto;\n\
         \t};\n\
         \tcreate_workspace: {\n\
         \t\tinput: CreateWorkspaceInput;\n\
         \t\toutput: WorkspaceSnapshotDto;\n\
         \t};\n\
         \trename_workspace: {\n\
         \t\tinput: RenameWorkspaceInput;\n\
         \t\toutput: WorkspaceSnapshotDto;\n\
         \t};\n\
         \tset_workspace_base_directory: {\n\
         \t\tinput: SetWorkspaceBaseDirectoryInput;\n\
         \t\toutput: WorkspaceSnapshotDto;\n\
         \t};\n\
         \tswitch_workspace: {\n\
         \t\tinput: WorkspaceIdInput;\n\
         \t\toutput: WorkspaceSnapshotDto;\n\
         \t};\n\
         \tdelete_workspace: {\n\
         \t\tinput: WorkspaceIdInput;\n\
         \t\toutput: WorkspaceSnapshotDto;\n\
         \t};\n\
         };\n",
    );
    contract.push_str(
        "\nexport type RequestCommandContracts = {\n\
         \tlist_request_workspace: {\n\
         \t\tinput: WorkspaceIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \topen_unsaved_request_tab: {\n\
         \t\tinput: WorkspaceIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tcreate_saved_request: {\n\
         \t\tinput: CreateSavedRequestInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tcreate_collection_folder: {\n\
         \t\tinput: CreateCollectionFolderInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tselect_environment: {\n\
         \t\tinput: SelectEnvironmentInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tresolve_request_content: {\n\
         \t\tinput: ResolveRequestContentInput;\n\
         \t\toutput: ResolvedRequestContentDto;\n\
         \t};\n\
         \trename_collection_folder: {\n\
         \t\tinput: RenameCollectionFolderInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tmove_collection_folder: {\n\
         \t\tinput: MoveCollectionFolderInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tduplicate_collection_folder: {\n\
         \t\tinput: CollectionFolderIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tdelete_collection_folder: {\n\
         \t\tinput: CollectionFolderIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tmove_saved_request: {\n\
         \t\tinput: MoveSavedRequestInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tduplicate_saved_request: {\n\
         \t\tinput: SavedRequestIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tdelete_saved_request: {\n\
         \t\tinput: SavedRequestIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \topen_saved_request_tab: {\n\
         \t\tinput: OpenSavedRequestTabInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tupdate_request_draft: {\n\
         \t\tinput: UpdateRequestDraftInput;\n\
         \t\toutput: undefined;\n\
         \t};\n\
         \tflush_request_drafts: {\n\
         \t\tinput: undefined;\n\
         \t\toutput: undefined;\n\
         \t};\n\
         \tsave_request_draft: {\n\
         \t\tinput: RequestDraftIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tclose_request_tab: {\n\
         \t\tinput: CloseRequestTabInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tlist_execution_history: {\n\
         \t\tinput: WorkspaceIdInput;\n\
         \t\toutput: ExecutionHistorySnapshotDto;\n\
         \t};\n\
         \tset_execution_history_disabled: {\n\
         \t\tinput: SetExecutionHistoryDisabledInput;\n\
         \t\toutput: ExecutionHistorySnapshotDto;\n\
         \t};\n\
         \tset_execution_record_pinned: {\n\
         \t\tinput: SetExecutionRecordPinnedInput;\n\
         \t\toutput: ExecutionHistorySnapshotDto;\n\
         \t};\n\
         \topen_execution_record_as_draft: {\n\
         \t\tinput: ExecutionRecordIdInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tlist_cookies: {\n\
         \t\tinput: WorkspaceIdInput;\n\
         \t\toutput: CookieJarSnapshotDto;\n\
         \t};\n\
         \tupsert_cookie: {\n\
         \t\tinput: UpsertCookieInput;\n\
         \t\toutput: CookieJarSnapshotDto;\n\
         \t};\n\
         \tdelete_cookie: {\n\
         \t\tinput: CookieIdInput;\n\
         \t\toutput: CookieJarSnapshotDto;\n\
         \t};\n\
         \tclear_cookies: {\n\
         \t\tinput: WorkspaceIdInput;\n\
         \t\toutput: CookieJarSnapshotDto;\n\
         \t};\n\
         \treveal_cookie_value: {\n\
         \t\tinput: CookieIdInput;\n\
         \t\toutput: RevealCookieValueOutput;\n\
         \t};\n\
         \tdescribe_body_file: {\n\
         \t\tinput: DescribeBodyFileInput;\n\
         \t\toutput: BodyFileReferenceDto;\n\
         \t};\n\
         \trelink_body_files: {\n\
         \t\tinput: RelinkBodyFilesInput;\n\
         \t\toutput: RequestWorkspaceSnapshotDto;\n\
         \t};\n\
         \tpreview_postman_import: {\n\
         \t\tinput: PostmanImportInput;\n\
         \t\toutput: PostmanImportPreviewDto;\n\
         \t};\n\
         \timport_postman: {\n\
         \t\tinput: PostmanImportInput;\n\
         \t\toutput: PostmanImportResultDto;\n\
         \t};\n\
         \texport_postman: {\n\
         \t\tinput: PostmanExportInput;\n\
         \t\toutput: PostmanExportResultDto;\n\
         \t};\n\
         \tpreview_postman_reimport: {\n\
         \t\tinput: PostmanImportInput;\n\
         \t\toutput: PostmanReimportPreviewDto;\n\
         \t};\n\
         \treimport_postman: {\n\
         \t\tinput: PostmanReimportInput;\n\
         \t\toutput: PostmanReimportResultDto;\n\
         \t};\n\
         \texport_native_backup: {\n\
         \t\tinput: NativeBackupExportInput;\n\
         \t\toutput: NativeBackupExportResultDto;\n\
         \t};\n\
         \tpreview_native_backup_restore: {\n\
         \t\tinput: NativeBackupRestorePreviewInput;\n\
         \t\toutput: NativeBackupRestorePreviewDto;\n\
         \t};\n\
         \trestore_native_backup: {\n\
         \t\tinput: NativeBackupRestoreInput;\n\
         \t\toutput: NativeBackupRestoreResultDto;\n\
         \t};\n\
         \tget_database_recovery_state: {\n\
         \t\tinput: undefined;\n\
         \t\toutput: DatabaseRecoveryStateDto;\n\
         \t};\n\
         \texport_recoverable_database: {\n\
         \t\tinput: RecoverableDatabaseExportInput;\n\
         \t\toutput: RecoverableDatabaseExportDto;\n\
         \t};\n\
         \tget_diagnostic_bundle_preview: {\n\
         \t\tinput: undefined;\n\
         \t\toutput: DiagnosticBundlePreviewDto;\n\
         \t};\n\
         \tset_diagnostic_debug_logging: {\n\
         \t\tinput: DiagnosticDebugLoggingInput;\n\
         \t\toutput: DiagnosticDebugLoggingStatusDto;\n\
         \t};\n\
         \texport_diagnostic_bundle: {\n\
         \t\tinput: DiagnosticBundleExportInput;\n\
         \t\toutput: DiagnosticBundleExportDto;\n\
         \t};\n\
         \tcheck_for_update: {\n\
         \t\tinput: undefined;\n\
         \t\toutput: UpdateCheckResultDto;\n\
         \t};\n\
         \tpreview_curl_import: {\n\
         \t\tinput: CurlImportInput;\n\
         \t\toutput: CurlImportPreviewDto;\n\
         \t};\n\
         \timport_curl_as_draft: {\n\
         \t\tinput: CurlImportInput;\n\
         \t\toutput: CurlImportResultDto;\n\
         \t};\n\
         \tgenerate_curl: {\n\
         \t\tinput: CurlGenerateInput;\n\
         \t\toutput: CurlGenerateResultDto;\n\
         \t};\n\
         \tstart_request_execution: {\n\
         \t\tinput: StartRequestExecutionInput;\n\
         \t\toutput: StartRequestExecutionOutput;\n\
         \t};\n\
         \tcancel_request_execution: {\n\
         \t\tinput: CancelRequestExecutionInput;\n\
         \t\toutput: CancelRequestExecutionOutput;\n\
         \t};\n\
         \tsave_response_file: {\n\
         \t\tinput: SaveResponseFileInput;\n\
         \t\toutput: SaveResponseFileOutput;\n\
         \t};\n\
         \tstart_oauth_authorization: {\n\
         \t\tinput: StartOAuthAuthorizationInput;\n\
         \t\toutput: OAuthAuthorizationResultDto;\n\
         \t};\n\
         \tcancel_oauth_authorization: {\n\
         \t\tinput: CancelOAuthAuthorizationInput;\n\
         \t\toutput: CancelOAuthAuthorizationOutput;\n\
         \t};\n\
         };\n\n\
         export type IpcCommandContracts = WorkspaceCommandContracts & RequestCommandContracts;\n",
    );

    Ok(contract)
}

fn parse_workspace_id(value: &str) -> Result<WorkspaceId, IpcError> {
    WorkspaceId::from_str(value).map_err(|_| BoundaryError::InvalidWorkspaceId.into())
}

fn parse_collection_id(value: &str) -> Result<CollectionId, IpcError> {
    CollectionId::from_str(value).map_err(|_| BoundaryError::InvalidCollectionId.into())
}

fn parse_optional_collection_id(value: Option<String>) -> Result<Option<CollectionId>, IpcError> {
    value.as_deref().map(parse_collection_id).transpose()
}

fn parse_environment_id(value: &str) -> Result<EnvironmentId, IpcError> {
    EnvironmentId::from_str(value).map_err(|_| BoundaryError::InvalidEnvironmentId.into())
}

fn parse_optional_environment_id(value: Option<String>) -> Result<Option<EnvironmentId>, IpcError> {
    value.as_deref().map(parse_environment_id).transpose()
}

fn parse_saved_request_id(value: &str) -> Result<SavedRequestId, IpcError> {
    SavedRequestId::from_str(value).map_err(|_| BoundaryError::InvalidSavedRequestId.into())
}

fn parse_request_draft_id(value: &str) -> Result<RequestDraftId, IpcError> {
    RequestDraftId::from_str(value).map_err(|_| BoundaryError::InvalidRequestDraftId.into())
}

fn parse_request_tab_id(value: &str) -> Result<RequestTabId, IpcError> {
    RequestTabId::from_str(value).map_err(|_| BoundaryError::InvalidRequestTabId.into())
}

fn parse_execution_id(value: &str) -> Result<ExecutionId, IpcError> {
    ExecutionId::from_str(value).map_err(|_| BoundaryError::InvalidExecutionId.into())
}

fn parse_oauth_flow_id(value: &str) -> Result<OAuthFlowId, IpcError> {
    OAuthFlowId::from_str(value).map_err(|_| BoundaryError::InvalidOAuthFlowId.into())
}

fn parse_execution_record_id(value: &str) -> Result<ExecutionRecordId, IpcError> {
    ExecutionRecordId::from_str(value).map_err(|_| BoundaryError::InvalidExecutionRecordId.into())
}

fn parse_cookie_id(value: &str) -> Result<CookieId, IpcError> {
    CookieId::from_str(value).map_err(|_| BoundaryError::InvalidCookieId.into())
}

fn map_poison_error<T>(_error: PoisonError<T>) -> IpcError {
    BoundaryError::StateUnavailable.into()
}

impl From<WorkspaceSnapshot> for WorkspaceSnapshotDto {
    fn from(snapshot: WorkspaceSnapshot) -> Self {
        Self {
            selected_workspace_id: snapshot.selected_workspace_id.to_string(),
            workspaces: snapshot
                .workspaces
                .into_iter()
                .map(|workspace| WorkspaceSummaryDto {
                    id: workspace.id.to_string(),
                    name: workspace.name.to_string(),
                    is_selected: workspace.is_selected,
                    base_directory: workspace.base_directory,
                })
                .collect(),
        }
    }
}

impl From<RequestWorkspaceSnapshot> for RequestWorkspaceSnapshotDto {
    fn from(snapshot: RequestWorkspaceSnapshot) -> Self {
        Self {
            workspace_id: snapshot.workspace_id.to_string(),
            collection_folders: snapshot
                .collection_folders
                .into_iter()
                .map(CollectionFolderDto::from)
                .collect(),
            environments: snapshot
                .environments
                .into_iter()
                .map(EnvironmentDto::from)
                .collect(),
            collection_variables: snapshot
                .collection_variables
                .into_iter()
                .map(CollectionVariableDto::from)
                .collect(),
            environment_variables: snapshot
                .environment_variables
                .into_iter()
                .map(EnvironmentVariableDto::from)
                .collect(),
            saved_requests: snapshot
                .saved_requests
                .into_iter()
                .map(SavedRequestDto::from)
                .collect(),
            drafts: snapshot
                .drafts
                .into_iter()
                .map(RequestDraftDto::from)
                .collect(),
            tabs: snapshot.tabs.into_iter().map(RequestTabDto::from).collect(),
        }
    }
}

impl TryFrom<PostmanImportInput> for ApplicationPostmanImportInput {
    type Error = IpcError;

    fn try_from(input: PostmanImportInput) -> Result<Self, Self::Error> {
        Ok(Self {
            workspace_id: parse_workspace_id(&input.workspace_id)?,
            source_name: input.source_name,
            collection_json: input.collection_json,
            environment_json: input.environment_json,
        })
    }
}

impl TryFrom<PostmanExportInput> for ApplicationPostmanExportInput {
    type Error = IpcError;

    fn try_from(input: PostmanExportInput) -> Result<Self, Self::Error> {
        Ok(Self {
            workspace_id: parse_workspace_id(&input.workspace_id)?,
            source_name: input.source_name,
        })
    }
}

impl From<PostmanExportResult> for PostmanExportResultDto {
    fn from(result: PostmanExportResult) -> Self {
        Self {
            collection_json: result.collection_json,
            environments: result
                .environments
                .into_iter()
                .map(PostmanEnvironmentExportDto::from)
                .collect(),
            warning_count: result.warning_count,
            unsupported_count: result.unsupported_count,
            warnings: result
                .warnings
                .into_iter()
                .map(PostmanImportWarningDto::from)
                .collect(),
            unsupported: result
                .unsupported
                .into_iter()
                .map(PostmanUnsupportedFieldDto::from)
                .collect(),
        }
    }
}

impl From<PostmanEnvironmentExport> for PostmanEnvironmentExportDto {
    fn from(environment: PostmanEnvironmentExport) -> Self {
        Self {
            name: environment.name,
            environment_json: environment.environment_json,
        }
    }
}

impl From<PostmanImportPreview> for PostmanImportPreviewDto {
    fn from(preview: PostmanImportPreview) -> Self {
        Self {
            source_id: preview.source_id,
            source_name: preview.source_name,
            source_hash: preview.source_hash,
            collection_count: preview.collection_count,
            request_count: preview.request_count,
            environment_count: preview.environment_count,
            warning_count: preview.warning_count,
            unsupported_count: preview.unsupported_count,
            warnings: preview
                .warnings
                .into_iter()
                .map(PostmanImportWarningDto::from)
                .collect(),
            unsupported: preview
                .unsupported
                .into_iter()
                .map(PostmanUnsupportedFieldDto::from)
                .collect(),
        }
    }
}

impl From<PostmanImportWarning> for PostmanImportWarningDto {
    fn from(warning: PostmanImportWarning) -> Self {
        Self {
            location: warning.location,
            message: warning.message,
        }
    }
}

impl From<PostmanUnsupportedField> for PostmanUnsupportedFieldDto {
    fn from(field: PostmanUnsupportedField) -> Self {
        Self {
            location: field.location,
            reason: field.reason,
        }
    }
}

impl From<PostmanImportResult> for PostmanImportResultDto {
    fn from(result: PostmanImportResult) -> Self {
        Self {
            preview: PostmanImportPreviewDto::from(result.preview),
            snapshot: RequestWorkspaceSnapshotDto::from(result.snapshot),
        }
    }
}

impl From<PostmanReimportPreview> for PostmanReimportPreviewDto {
    fn from(preview: PostmanReimportPreview) -> Self {
        Self {
            import_preview: PostmanImportPreviewDto::from(preview.import_preview),
            prior_import: preview.prior_import.map(PostmanPriorImportDto::from),
            changes: preview
                .changes
                .into_iter()
                .map(PostmanReimportChangeDto::from)
                .collect(),
            can_update: preview.can_update,
        }
    }
}

impl From<PostmanPriorImport> for PostmanPriorImportDto {
    fn from(prior: PostmanPriorImport) -> Self {
        Self {
            id: prior.id,
            source_id: prior.source_id,
            source_name: prior.source_name,
            source_hash: prior.source_hash,
        }
    }
}

impl From<PostmanReimportChange> for PostmanReimportChangeDto {
    fn from(change: PostmanReimportChange) -> Self {
        Self {
            location: change.location,
            message: change.message,
        }
    }
}

impl From<PostmanReimportDecisionDto> for PostmanReimportDecision {
    fn from(decision: PostmanReimportDecisionDto) -> Self {
        match decision {
            PostmanReimportDecisionDto::Update => Self::Update,
            PostmanReimportDecisionDto::Duplicate => Self::Duplicate,
            PostmanReimportDecisionDto::Cancel => Self::Cancel,
        }
    }
}

impl TryFrom<PostmanReimportInput> for ApplicationPostmanReimportInput {
    type Error = IpcError;

    fn try_from(input: PostmanReimportInput) -> Result<Self, Self::Error> {
        Ok(Self {
            import: ApplicationPostmanImportInput::try_from(input.import)?,
            decision: PostmanReimportDecision::from(input.decision),
        })
    }
}

impl From<PostmanReimportResult> for PostmanReimportResultDto {
    fn from(result: PostmanReimportResult) -> Self {
        Self {
            preview: PostmanReimportPreviewDto::from(result.preview),
            snapshot: RequestWorkspaceSnapshotDto::from(result.snapshot),
        }
    }
}

impl TryFrom<NativeBackupExportInput> for ApplicationNativeBackupExportInput {
    type Error = IpcError;

    fn try_from(input: NativeBackupExportInput) -> Result<Self, Self::Error> {
        Ok(Self {
            workspace_id: parse_workspace_id(&input.workspace_id)?,
            backup_path: input.backup_path,
            include_body_files: input.include_body_files,
            body_files_directory: input.body_files_directory,
        })
    }
}

impl From<NativeBackupExportResult> for NativeBackupExportResultDto {
    fn from(result: NativeBackupExportResult) -> Self {
        Self {
            backup_path: result.backup_path,
            manifest: NativeBackupManifestDto::from(result.manifest),
            preview: NativeBackupRestorePreviewDto::from(result.preview),
        }
    }
}

impl From<NativeBackupRestoreResult> for NativeBackupRestoreResultDto {
    fn from(result: NativeBackupRestoreResult) -> Self {
        Self {
            preview: NativeBackupRestorePreviewDto::from(result.preview),
            workspace_snapshot: WorkspaceSnapshotDto::from(result.workspace_snapshot),
            request_snapshot: RequestWorkspaceSnapshotDto::from(result.request_snapshot),
        }
    }
}

impl From<NativeBackupRestorePreview> for NativeBackupRestorePreviewDto {
    fn from(preview: NativeBackupRestorePreview) -> Self {
        Self {
            source_workspace_name: preview.source_workspace_name,
            collection_count: preview.collection_count,
            request_count: preview.request_count,
            environment_count: preview.environment_count,
            history_record_count: preview.history_record_count,
            cookie_count: preview.cookie_count,
            body_file_count: preview.body_file_count,
            expanded_bytes: preview.expanded_bytes,
            exclusions: preview
                .exclusions
                .into_iter()
                .map(NativeBackupExclusionDto::from)
                .collect(),
            warnings: preview.warnings,
        }
    }
}

impl From<NativeBackupExclusion> for NativeBackupExclusionDto {
    fn from(exclusion: NativeBackupExclusion) -> Self {
        Self {
            location: exclusion.location,
            reason: exclusion.reason,
        }
    }
}

impl From<NativeBackupManifest> for NativeBackupManifestDto {
    fn from(manifest: NativeBackupManifest) -> Self {
        Self {
            format: manifest.format,
            version: manifest.version,
            required_features: manifest.required_features,
            entries: manifest
                .entries
                .into_iter()
                .map(NativeBackupManifestEntryDto::from)
                .collect(),
            exclusions: manifest
                .exclusions
                .into_iter()
                .map(NativeBackupExclusionDto::from)
                .collect(),
        }
    }
}

impl From<NativeBackupManifestEntry> for NativeBackupManifestEntryDto {
    fn from(entry: NativeBackupManifestEntry) -> Self {
        Self {
            path: entry.path,
            sha256: entry.sha256,
            bytes: entry.bytes,
        }
    }
}

impl From<DatabaseRecoveryState> for DatabaseRecoveryStateDto {
    fn from(state: DatabaseRecoveryState) -> Self {
        Self {
            mode: DatabaseRecoveryModeDto::from(state.mode),
            reason: state.reason,
            snapshots: state.snapshots,
        }
    }
}

impl From<DatabaseRecoveryMode> for DatabaseRecoveryModeDto {
    fn from(mode: DatabaseRecoveryMode) -> Self {
        match mode {
            DatabaseRecoveryMode::Normal => Self::Normal,
            DatabaseRecoveryMode::Safe => Self::Safe,
        }
    }
}

impl From<ApplicationRecoverableDatabaseExport> for RecoverableDatabaseExportDto {
    fn from(export: ApplicationRecoverableDatabaseExport) -> Self {
        Self {
            export_path: export.export_path,
            source_path: export.source_path,
            repaired_copy_path: export.repaired_copy_path,
            table_count: export.table_count,
            row_count: export.row_count,
            redacted_value_count: export.redacted_value_count,
        }
    }
}

impl From<DiagnosticBundlePreview> for DiagnosticBundlePreviewDto {
    fn from(preview: DiagnosticBundlePreview) -> Self {
        Self {
            entries: preview.entries,
            exclusions: preview.exclusions,
            debug_logging_enabled: preview.debug_logging_enabled,
        }
    }
}

impl From<DebugLoggingStatus> for DiagnosticDebugLoggingStatusDto {
    fn from(status: DebugLoggingStatus) -> Self {
        Self {
            enabled: status.enabled,
            expires_at_epoch_seconds: status.expires_at_epoch_seconds,
        }
    }
}

impl From<DiagnosticBundleExport> for DiagnosticBundleExportDto {
    fn from(result: DiagnosticBundleExport) -> Self {
        Self {
            bundle_path: result.bundle_path,
            preview: result.preview.into(),
        }
    }
}

impl From<crate::application::update::UpdateCheckResult> for UpdateCheckResultDto {
    fn from(result: crate::application::update::UpdateCheckResult) -> Self {
        Self {
            latest_version: result.latest_version,
            update_available: result.update_available,
        }
    }
}

impl TryFrom<CurlImportInput> for ApplicationCurlImportInput {
    type Error = IpcError;

    fn try_from(input: CurlImportInput) -> Result<Self, Self::Error> {
        Ok(Self {
            workspace_id: parse_workspace_id(&input.workspace_id)?,
            source_name: input.source_name,
            command: input.command,
        })
    }
}

impl From<CurlGenerateInput> for ApplicationCurlGenerateInput {
    fn from(input: CurlGenerateInput) -> Self {
        let content = RequestContent::from(input.content);
        let resolved = input
            .resolved
            .map(|resolved| resolved_request_content_from_dto(resolved, &content));
        Self {
            content,
            resolved,
            include_secrets: input.include_secrets,
        }
    }
}

impl From<CurlImportPreview> for CurlImportPreviewDto {
    fn from(preview: CurlImportPreview) -> Self {
        Self {
            source_name: preview.source_name,
            content: RequestContentDto::from(preview.content),
            warning_count: preview.warning_count,
            unsupported_count: preview.unsupported_count,
            warnings: preview
                .warnings
                .into_iter()
                .map(CurlImportWarningDto::from)
                .collect(),
            unsupported: preview
                .unsupported
                .into_iter()
                .map(CurlUnsupportedFieldDto::from)
                .collect(),
        }
    }
}

impl From<CurlImportWarning> for CurlImportWarningDto {
    fn from(warning: CurlImportWarning) -> Self {
        Self {
            location: warning.location,
            message: warning.message,
        }
    }
}

impl From<CurlUnsupportedField> for CurlUnsupportedFieldDto {
    fn from(field: CurlUnsupportedField) -> Self {
        Self {
            location: field.location,
            reason: field.reason,
        }
    }
}

impl From<CurlGenerateResult> for CurlGenerateResultDto {
    fn from(result: CurlGenerateResult) -> Self {
        Self {
            command: result.command,
            included_secret_count: result.included_secret_count,
            redacted_secret_count: result.redacted_secret_count,
        }
    }
}
